// offlineNames.js — bundled name / sector / region for large S&P 500 names and
// TSX 60 names. Used only when a live lookup cannot verify the ticker.
// Sectors match the app's GICS list. The label tells the user to edit a miss
// — index membership drifts, and this file is a suggestion, not a feed.

const IT = 'Information Technology';
const FIN = 'Financials';
const HC = 'Health Care';
const CD = 'Consumer Discretionary';
const CS = 'Consumer Staples';
const COM = 'Communication Services';
const EN = 'Energy';
const IND = 'Industrials';
const MAT = 'Materials';
const UTIL = 'Utilities';
const RE = 'Real Estate';
const US = 'United States';
const CA = 'Canada';

// [symbol, name, sector]
const US_LARGE = [
  ['AAPL', 'Apple Inc.', IT],
  ['MSFT', 'Microsoft Corporation', IT],
  ['NVDA', 'NVIDIA Corporation', IT],
  ['AMZN', 'Amazon.com, Inc.', CD],
  ['GOOGL', 'Alphabet Inc.', COM],
  ['GOOG', 'Alphabet Inc.', COM],
  ['META', 'Meta Platforms, Inc.', COM],
  ['AVGO', 'Broadcom Inc.', IT],
  ['TSLA', 'Tesla, Inc.', CD],
  ['BRK.B', 'Berkshire Hathaway Inc.', FIN],
  ['JPM', 'JPMorgan Chase & Co.', FIN],
  ['LLY', 'Eli Lilly and Company', HC],
  ['V', 'Visa Inc.', FIN],
  ['UNH', 'UnitedHealth Group Incorporated', HC],
  ['XOM', 'Exxon Mobil Corporation', EN],
  ['MA', 'Mastercard Incorporated', FIN],
  ['JNJ', 'Johnson & Johnson', HC],
  ['COST', 'Costco Wholesale Corporation', CS],
  ['HD', 'The Home Depot, Inc.', CD],
  ['PG', 'The Procter & Gamble Company', CS],
  ['NFLX', 'Netflix, Inc.', COM],
  ['ABBV', 'AbbVie Inc.', HC],
  ['BAC', 'Bank of America Corporation', FIN],
  ['CRM', 'Salesforce, Inc.', IT],
  ['KO', 'The Coca-Cola Company', CS],
  ['ORCL', 'Oracle Corporation', IT],
  ['CVX', 'Chevron Corporation', EN],
  ['AMD', 'Advanced Micro Devices, Inc.', IT],
  ['WMT', 'Walmart Inc.', CS],
  ['MRK', 'Merck & Co., Inc.', HC],
  ['PEP', 'PepsiCo, Inc.', CS],
  ['TMO', 'Thermo Fisher Scientific Inc.', HC],
  ['LIN', 'Linde plc', MAT],
  ['ACN', 'Accenture plc', IT],
  ['MCD', "McDonald's Corporation", CD],
  ['CSCO', 'Cisco Systems, Inc.', IT],
  ['ABT', 'Abbott Laboratories', HC],
  ['IBM', 'International Business Machines Corporation', IT],
  ['GE', 'GE Aerospace', IND],
  ['CAT', 'Caterpillar Inc.', IND],
  ['NOW', 'ServiceNow, Inc.', IT],
  ['AXP', 'American Express Company', FIN],
  ['DIS', 'The Walt Disney Company', COM],
  ['PM', 'Philip Morris International Inc.', CS],
  ['GS', 'The Goldman Sachs Group, Inc.', FIN],
  ['ISRG', 'Intuitive Surgical, Inc.', HC],
  ['INTU', 'Intuit Inc.', IT],
  ['TXN', 'Texas Instruments Incorporated', IT],
  ['BKNG', 'Booking Holdings Inc.', CD],
  ['QCOM', 'QUALCOMM Incorporated', IT],
  ['AMGN', 'Amgen Inc.', HC],
  ['VZ', 'Verizon Communications Inc.', COM],
  ['T', 'AT&T Inc.', COM],
  ['PFE', 'Pfizer Inc.', HC],
  ['MS', 'Morgan Stanley', FIN],
  ['NEE', 'NextEra Energy, Inc.', UTIL],
  ['RTX', 'RTX Corporation', IND],
  ['SPGI', 'S&P Global Inc.', FIN],
  ['LOW', "Lowe's Companies, Inc.", CD],
  ['HON', 'Honeywell International Inc.', IND],
  ['UNP', 'Union Pacific Corporation', IND],
  ['AMAT', 'Applied Materials, Inc.', IT],
  ['BLK', 'BlackRock, Inc.', FIN],
  ['SYK', 'Stryker Corporation', HC],
  ['ELV', 'Elevance Health, Inc.', HC],
  ['PGR', 'The Progressive Corporation', FIN],
  ['SCHW', 'The Charles Schwab Corporation', FIN],
  ['C', 'Citigroup Inc.', FIN],
  ['BA', 'The Boeing Company', IND],
  ['DE', 'Deere & Company', IND],
  ['ADP', 'Automatic Data Processing, Inc.', IND],
  ['GILD', 'Gilead Sciences, Inc.', HC],
  ['ADI', 'Analog Devices, Inc.', IT],
  ['MMC', 'Marsh & McLennan Companies, Inc.', FIN],
  ['LMT', 'Lockheed Martin Corporation', IND],
  ['CB', 'Chubb Limited', FIN],
  ['VRTX', 'Vertex Pharmaceuticals Incorporated', HC],
  ['ETN', 'Eaton Corporation plc', IND],
  ['REGN', 'Regeneron Pharmaceuticals, Inc.', HC],
  ['BMY', 'Bristol-Myers Squibb Company', HC],
  ['PANW', 'Palo Alto Networks, Inc.', IT],
  ['PLD', 'Prologis, Inc.', RE],
  ['CI', 'The Cigna Group', HC],
  ['SO', 'The Southern Company', UTIL],
  ['DUK', 'Duke Energy Corporation', UTIL],
  ['MO', 'Altria Group, Inc.', CS],
  ['CL', 'Colgate-Palmolive Company', CS],
  ['ZTS', 'Zoetis Inc.', HC],
  ['CME', 'CME Group Inc.', FIN],
  ['EQIX', 'Equinix, Inc.', RE],
  ['SHW', 'The Sherwin-Williams Company', MAT],
  ['ITW', 'Illinois Tool Works Inc.', IND],
  ['WM', 'Waste Management, Inc.', IND],
  ['NOC', 'Northrop Grumman Corporation', IND],
  ['PH', 'Parker-Hannifin Corporation', IND],
  ['MCO', "Moody's Corporation", FIN],
  ['PYPL', 'PayPal Holdings, Inc.', FIN],
  ['INTC', 'Intel Corporation', IT],
  ['NKE', 'NIKE, Inc.', CD],
  ['SBUX', 'Starbucks Corporation', CD],
  ['MDT', 'Medtronic plc', HC],
  ['UPS', 'United Parcel Service, Inc.', IND],
  ['CVS', 'CVS Health Corporation', HC],
  ['AMT', 'American Tower Corporation', RE],
  ['TGT', 'Target Corporation', CD],
  ['USB', 'U.S. Bancorp', FIN],
  ['GD', 'General Dynamics Corporation', IND],
  ['APD', 'Air Products and Chemicals, Inc.', MAT],
  ['EOG', 'EOG Resources, Inc.', EN],
  ['SLB', 'SLB N.V.', EN],
  ['COP', 'ConocoPhillips', EN],
  ['MPC', 'Marathon Petroleum Corporation', EN],
  ['PSX', 'Phillips 66', EN],
  ['OXY', 'Occidental Petroleum Corporation', EN],
  ['F', 'Ford Motor Company', CD],
  ['GM', 'General Motors Company', CD],
  ['UBER', 'Uber Technologies, Inc.', IND],
  ['ABNB', 'Airbnb, Inc.', CD],
  ['CRWD', 'CrowdStrike Holdings, Inc.', IT],
  ['PLTR', 'Palantir Technologies Inc.', IT],
  ['MU', 'Micron Technology, Inc.', IT],
  ['ANET', 'Arista Networks, Inc.', IT],
  ['KLAC', 'KLA Corporation', IT],
  ['LRCX', 'Lam Research Corporation', IT],
  ['SNPS', 'Synopsys, Inc.', IT],
  ['CDNS', 'Cadence Design Systems, Inc.', IT],
  ['ADBE', 'Adobe Inc.', IT],
  ['WFC', 'Wells Fargo & Company', FIN],
  ['BX', 'Blackstone Inc.', FIN],
  ['KKR', 'KKR & Co. Inc.', FIN],
  ['SPG', 'Simon Property Group, Inc.', RE],
  ['O', 'Realty Income Corporation', RE],
  ['WELL', 'Welltower Inc.', RE],
  ['DHR', 'Danaher Corporation', HC],
  ['BSX', 'Boston Scientific Corporation', HC],
  ['HCA', 'HCA Healthcare, Inc.', HC],
  ['MDLZ', 'Mondelez International, Inc.', CS],
  ['KMB', 'Kimberly-Clark Corporation', CS],
  ['GIS', 'General Mills, Inc.', CS],
  ['KHC', 'The Kraft Heinz Company', CS],
  ['NEM', 'Newmont Corporation', MAT],
  ['FCX', 'Freeport-McMoRan Inc.', MAT],
  ['NUE', 'Nucor Corporation', MAT],
  ['ECL', 'Ecolab Inc.', MAT],
  ['DOW', 'Dow Inc.', MAT],
  ['DD', 'DuPont de Nemours, Inc.', MAT],
  ['EMR', 'Emerson Electric Co.', IND],
  ['MMM', '3M Company', IND],
  ['ROP', 'Roper Technologies, Inc.', IT],
  ['TEL', 'TE Connectivity plc', IT],
  ['GLW', 'Corning Incorporated', IT],
  ['HPQ', 'HP Inc.', IT],
  ['DELL', 'Dell Technologies Inc.', IT],
  ['AON', 'Aon plc', FIN],
  ['AJG', 'Arthur J. Gallagher & Co.', FIN],
  ['MET', 'MetLife, Inc.', FIN],
  ['PRU', 'Prudential Financial, Inc.', FIN],
  ['AIG', 'American International Group, Inc.', FIN],
  ['ALL', 'The Allstate Corporation', FIN],
  ['TRV', 'The Travelers Companies, Inc.', FIN],
  ['AFL', 'Aflac Incorporated', FIN],
  ['ICE', 'Intercontinental Exchange, Inc.', FIN],
  ['MSCI', 'MSCI Inc.', FIN],
  ['TFC', 'Truist Financial Corporation', FIN],
  ['PNC', 'The PNC Financial Services Group, Inc.', FIN],
  ['COF', 'Capital One Financial Corporation', FIN],
  ['FI', 'Fiserv, Inc.', FIN],
  ['PAYX', 'Paychex, Inc.', IND],
  ['TJX', 'The TJX Companies, Inc.', CD],
  ['BK', 'The Bank of New York Mellon Corporation', FIN],
  ['CMG', 'Chipotle Mexican Grill, Inc.', CD],
  ['MAR', 'Marriott International, Inc.', CD],
  ['ORLY', "O'Reilly Automotive, Inc.", CD],
  ['ADSK', 'Autodesk, Inc.', IT],
  ['FTNT', 'Fortinet, Inc.', IT],
  ['MNST', 'Monster Beverage Corporation', CS],
  ['AEP', 'American Electric Power Company, Inc.', UTIL],
  ['EXC', 'Exelon Corporation', UTIL],
  ['SRE', 'Sempra', UTIL],
  ['PCG', 'PG&E Corporation', UTIL],
  ['D', 'Dominion Energy, Inc.', UTIL],
  ['A', 'Agilent Technologies, Inc.', HC],
  ['BDX', 'Becton, Dickinson and Company', HC],
  ['EW', 'Edwards Lifesciences Corporation', HC],
  ['IDXX', 'IDEXX Laboratories, Inc.', HC],
  ['HUM', 'Humana Inc.', HC],
  ['CNC', 'Centene Corporation', HC],
  ['MRNA', 'Moderna, Inc.', HC],
  ['NXPI', 'NXP Semiconductors N.V.', IT],
  ['MCHP', 'Microchip Technology Incorporated', IT],
  ['ON', 'ON Semiconductor Corporation', IT],
  ['APH', 'Amphenol Corporation', IT],
  ['MSI', 'Motorola Solutions, Inc.', IT],
  ['CTAS', 'Cintas Corporation', IND],
  ['FAST', 'Fastenal Company', IND],
  ['PCAR', 'PACCAR Inc', IND],
  ['NSC', 'Norfolk Southern Corporation', IND],
  ['CSX', 'CSX Corporation', IND],
  ['FDX', 'FedEx Corporation', IND],
  ['DAL', 'Delta Air Lines, Inc.', IND],
  ['UAL', 'United Airlines Holdings, Inc.', IND],
  ['LUV', 'Southwest Airlines Co.', IND],
  ['NOC', 'Northrop Grumman Corporation', IND],
];

// NYSE/Nasdaq lines of Canadian companies. Region stays Canada (the business),
// while a bare ticker still infers USD when lookup fails.
const US_LISTED_CA = [
  ['RY', 'Royal Bank of Canada', FIN],
  ['TD', 'The Toronto-Dominion Bank', FIN],
  ['BMO', 'Bank of Montreal', FIN],
  ['BNS', 'The Bank of Nova Scotia', FIN],
  ['CM', 'Canadian Imperial Bank of Commerce', FIN],
  ['ENB', 'Enbridge Inc.', EN],
  ['TRP', 'TC Energy Corporation', EN],
  ['SU', 'Suncor Energy Inc.', EN],
  ['CNQ', 'Canadian Natural Resources Limited', EN],
  ['CVE', 'Cenovus Energy Inc.', EN],
  ['MFC', 'Manulife Financial Corporation', FIN],
  ['SLF', 'Sun Life Financial Inc.', FIN],
  ['SHOP', 'Shopify Inc.', IT],
  ['CNI', 'Canadian National Railway Company', IND],
  ['CP', 'Canadian Pacific Kansas City Limited', IND],
  ['TRI', 'Thomson Reuters Corporation', IND],
  ['BAM', 'Brookfield Asset Management Ltd.', FIN],
  ['BN', 'Brookfield Corporation', FIN],
  ['WCN', 'Waste Connections, Inc.', IND],
  ['NTR', 'Nutrien Ltd.', MAT],
  ['AEM', 'Agnico Eagle Mines Limited', MAT],
  ['FNV', 'Franco-Nevada Corporation', MAT],
  ['WPM', 'Wheaton Precious Metals Corp.', MAT],
  ['TECK', 'Teck Resources Limited', MAT],
  ['QSR', 'Restaurant Brands International Inc.', CD],
  ['BCE', 'BCE Inc.', COM],
  ['TU', 'TELUS Corporation', COM],
];

const TSX = [
  ['RY.TO', 'Royal Bank of Canada', FIN],
  ['TD.TO', 'The Toronto-Dominion Bank', FIN],
  ['BNS.TO', 'The Bank of Nova Scotia', FIN],
  ['BMO.TO', 'Bank of Montreal', FIN],
  ['CM.TO', 'Canadian Imperial Bank of Commerce', FIN],
  ['NA.TO', 'National Bank of Canada', FIN],
  ['MFC.TO', 'Manulife Financial Corporation', FIN],
  ['SLF.TO', 'Sun Life Financial Inc.', FIN],
  ['GWO.TO', 'Great-West Lifeco Inc.', FIN],
  ['IFC.TO', 'Intact Financial Corporation', FIN],
  ['FFH.TO', 'Fairfax Financial Holdings Limited', FIN],
  ['POW.TO', 'Power Corporation of Canada', FIN],
  ['IAG.TO', 'iA Financial Corporation Inc.', FIN],
  ['BAM.TO', 'Brookfield Asset Management Ltd.', FIN],
  ['BN.TO', 'Brookfield Corporation', FIN],
  ['X.TO', 'TMX Group Limited', FIN],
  ['ENB.TO', 'Enbridge Inc.', EN],
  ['TRP.TO', 'TC Energy Corporation', EN],
  ['CNQ.TO', 'Canadian Natural Resources Limited', EN],
  ['SU.TO', 'Suncor Energy Inc.', EN],
  ['CVE.TO', 'Cenovus Energy Inc.', EN],
  ['IMO.TO', 'Imperial Oil Limited', EN],
  ['PPL.TO', 'Pembina Pipeline Corporation', EN],
  ['TOU.TO', 'Tourmaline Oil Corp.', EN],
  ['CCO.TO', 'Cameco Corporation', EN],
  ['KEY.TO', 'Keyera Corp.', EN],
  ['ARX.TO', 'ARC Resources Ltd.', EN],
  ['CNR.TO', 'Canadian National Railway Company', IND],
  ['CP.TO', 'Canadian Pacific Kansas City Limited', IND],
  ['WCN.TO', 'Waste Connections, Inc.', IND],
  ['TRI.TO', 'Thomson Reuters Corporation', IND],
  ['WSP.TO', 'WSP Global Inc.', IND],
  ['RBA.TO', 'RB Global, Inc.', IND],
  ['TFII.TO', 'TFI International Inc.', IND],
  ['TIH.TO', 'Toromont Industries Ltd.', IND],
  ['STN.TO', 'Stantec Inc.', IND],
  ['SHOP.TO', 'Shopify Inc.', IT],
  ['CSU.TO', 'Constellation Software Inc.', IT],
  ['OTEX.TO', 'Open Text Corporation', IT],
  ['GIB.A.TO', 'CGI Inc.', IT],
  ['CLS.TO', 'Celestica Inc.', IT],
  ['DSG.TO', 'The Descartes Systems Group Inc.', IT],
  ['BCE.TO', 'BCE Inc.', COM],
  ['T.TO', 'TELUS Corporation', COM],
  ['RCI.B.TO', 'Rogers Communications Inc.', COM],
  ['QSR.TO', 'Restaurant Brands International Inc.', CD],
  ['DOL.TO', 'Dollarama Inc.', CD],
  ['MG.TO', 'Magna International Inc.', CD],
  ['GIL.TO', 'Gildan Activewear Inc.', CD],
  ['CTC.A.TO', 'Canadian Tire Corporation, Limited', CD],
  ['ATD.TO', 'Alimentation Couche-Tard Inc.', CS],
  ['L.TO', 'Loblaw Companies Limited', CS],
  ['MRU.TO', 'Metro Inc.', CS],
  ['WN.TO', 'George Weston Limited', CS],
  ['SAP.TO', 'Saputo Inc.', CS],
  ['EMP.A.TO', 'Empire Company Limited', CS],
  ['NTR.TO', 'Nutrien Ltd.', MAT],
  ['ABX.TO', 'Barrick Gold Corporation', MAT],
  ['AEM.TO', 'Agnico Eagle Mines Limited', MAT],
  ['FNV.TO', 'Franco-Nevada Corporation', MAT],
  ['WPM.TO', 'Wheaton Precious Metals Corp.', MAT],
  ['K.TO', 'Kinross Gold Corporation', MAT],
  ['TECK.B.TO', 'Teck Resources Limited', MAT],
  ['FM.TO', 'First Quantum Minerals Ltd.', MAT],
  ['CCL.B.TO', 'CCL Industries Inc.', MAT],
  ['FTS.TO', 'Fortis Inc.', UTIL],
  ['H.TO', 'Hydro One Limited', UTIL],
  ['EMA.TO', 'Emera Incorporated', UTIL],
  ['CU.TO', 'Canadian Utilities Limited', UTIL],
  ['ALA.TO', 'AltaGas Ltd.', UTIL],
  ['AQN.TO', 'Algonquin Power & Utilities Corp.', UTIL],
  ['NPI.TO', 'Northland Power Inc.', UTIL],
  ['CAR.UN.TO', 'Canadian Apartment Properties REIT', RE],
  ['REI.UN.TO', 'RioCan Real Estate Investment Trust', RE],
  ['BIP.UN.TO', 'Brookfield Infrastructure Partners L.P.', IND],
];

export const SUGGESTED_LABEL = 'suggested, edit if wrong';

function addRows(map, rows, region) {
  for (const [symbol, name, sector] of rows) {
    map[String(symbol).toUpperCase()] = { name, sector, region };
  }
}

const CATALOG = {};
addRows(CATALOG, US_LARGE, US);
addRows(CATALOG, US_LISTED_CA, CA);
addRows(CATALOG, TSX, CA);

export const OFFLINE_NAMES = CATALOG;

export function offlineCatalogSize() {
  const symbols = Object.keys(OFFLINE_NAMES);
  return {
    total: symbols.length,
    us: symbols.filter((s) => !s.includes('.')).length,
    tsx: symbols.filter((s) => s.endsWith('.TO')).length,
  };
}

export function offlineLookup(symbol) {
  const key = String(symbol || '').trim().toUpperCase();
  if (!key) return null;
  const hit = OFFLINE_NAMES[key];
  if (!hit) return null;
  return { symbol: key, ...hit, label: SUGGESTED_LABEL };
}
